# Generated by Django 3.0.5 on 2021-10-18 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odata', '0002_auto_20211018_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='id',
            new_name='_id',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='id',
            new_name='_id',
        ),
        migrations.RenameField(
            model_name='newslettersubscription',
            old_name='id',
            new_name='_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='id',
            new_name='_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='id',
            new_name='_id',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='id',
            new_name='_id',
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='id',
            new_name='_id',
        ),
        migrations.RenameField(
            model_name='userforgotpassword',
            old_name='id',
            new_name='_id',
        ),
    ]
