# Generated by Django 3.0.5 on 2021-12-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odata', '0003_auto_20211018_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_id',
            field=models.CharField(max_length=250),
        ),
    ]
