# Generated by Django 3.0.5 on 2021-02-24 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odata', '0003_auto_20210224_0441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='Category_id',
        ),
    ]
