# Generated by Django 3.0.5 on 2021-03-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odata', '0005_auto_20210226_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
